name: environment
channels:
  - conda-forge
dependencies:
    - backcall==0.1.0
    - colorama==0.4.3
    - cycler==0.10.0
    - decorator==4.4.1
    - ipython==7.11.1
    - jedi==0.16.0
    - kiwisolver==1.1.0
    - matplotlib==3.1.2
    - mpmath==1.1.0
    - numpy==1.18.1
    - parso==0.6.0
    - pickleshare==0.7.5
    - pygments==2.5.2
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - six==1.14.0
    - sympy==1.5.1
    - traitlets==4.3.3
    - wcwidth==0.1.8


